FROM composer

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN set -eux; \
    install-php-extensions pdo_pgsql xdebug;

COPY ./xdebug.ini "${PHP_INI_DIR}/conf.d"

WORKDIR /app

COPY composer* ./

RUN composer install

COPY . .

CMD ["bash", "-c", "make start"]